### ISSUE TITLE
[Bubble Universe] Floppy image

### ISSUE THREAD

**Issue by bonnefoi** [movievertigo/movievertigo.github.io#1]
Hello,

could you put the different programs on a disk image, please ?
I want to try it on MiSTerFPGA.

Thank you for your awesome work !

**Comment by movievertigo** [comment]
Sure!  Here you go...
[https://movievertigo.github.io/downloads/riscos/bubbleuniverse/BubbleUniverse.adf](https://movievertigo.github.io/downloads/riscos/bubbleuniverse/BubbleUniverse.adf)

**Comment by bonnefoi** [comment]
Thank you very much !

It's working on the Archimedes core for MiSTerFPGA 👍
FPS : 11, Particles : 16384 for a resolution of 320x256 at 60Hz

**Comment by movievertigo** [comment]
Glad to hear it worked, and thanks for providing the stats!
